GG-33019 Introduce ProjectableFilterableTableScan
gridgain/gridgain-9-ce pull request #1
Opened 2021-04-14 16:09 UTC by tmagomedov

For native storage integration.

2021-04-14 16:24 UTC, vveider requested changes
It seems that after this commit, we will have to do IGNITE => CE sync with cherry-pick instead of FF?

2021-04-14 16:24 UTC, vveider commented on modules/sql/pom.xml
> +            <groupId>org.apache.ignite</groupId>
Internal dependencies should also be declared in parent pom's dependencyManagement section with version and here without.

2021-04-14 16:24 UTC, vveider commented on parent/pom.xml
> +        <calcite.version>1.26.0</calcite.version>
Version properties should be ABC sorted.

2021-05-19 11:09 UTC, AMashenkov commented on modules/sql/src/main/java/org/apache/ignite/internal/sql/rel/IgniteTableScan.java
> +    public IgniteTableScan(
Javadoc

2021-05-19 11:10 UTC, AMashenkov commented on modules/sql/src/main/java/org/apache/ignite/internal/sql/rel/ProjectableFilterableTableScan.java
> +    /** @return Projections. */
```suggestion
    /** 
    * @return Projections. 
    */
```

2021-05-19 11:10 UTC, AMashenkov commented on modules/sql/src/main/java/org/apache/ignite/internal/sql/rel/ProjectableFilterableTableScan.java
> +    /** @return Rex condition. */
```suggestion
    /** 
    * @return Rex condition. 
    */
```

2021-05-19 11:10 UTC, AMashenkov commented on modules/sql/src/main/java/org/apache/ignite/internal/sql/rel/ProjectableFilterableTableScan.java
> +    /** @return Participating columns. */
```suggestion
    /** 
    * @return Participating columns. 
    */
```

2021-05-19 11:11 UTC, AMashenkov commented on modules/sql/src/main/java/org/apache/ignite/internal/sql/rel/ProjectableFilterableTableScan.java
> +    /** */
Javadoc.

2021-05-20 12:56 UTC, tmagomedov commented
Looks like it is better to leave this repo code same as ignite-3 for now, closing merge request.

2021-05-20 12:56 UTC, closed without merging